# Generated by Django 5.2.7 on 2026-01-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('09-10', '09:00 - 10:00'), ('10-11', '10:00 - 11:00'), ('11-12', '11:00 - 12:00'), ('14-15', '02:00 - 03:00'), ('15-16', '03:00 - 04:00')], max_length=20, null=True),
        ),
    ]
