# Generated by Django 5.2.7 on 2026-01-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_appointment_date_appointment_time_slot'),
        ('doctor', '0003_remove_doctor_specialization_doctor_specializations'),
        ('patient', '0003_alter_patient_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'appointment_date', 'time_slot'), name='unique_patient_slot'),
        ),
    ]
