# Generated by Django 5.2.7 on 2026-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_unique_patient_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('09-10', '09:00 - 10:00'), ('10-11', '10:00 - 11:00'), ('11-12', '11:00 - 12:00'), ('14-15', '02:00 - 03:00'), ('15-16', '03:00 - 04:00'), ('16-17', '04:00 - 05:00')], max_length=20, null=True),
        ),
    ]
