# Generated by Django 5.2.7 on 2026-01-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_completed_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ppointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
