# Generated by Django 5.2.7 on 2026-01-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_notification_ppointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='ppointment',
            new_name='appointment',
        ),
    ]
