# Generated by Django 5.2.7 on 2026-01-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_rename_ppointment_notification_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
    ]
