# Generated by Django 5.2.7 on 2026-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
