# Generated by Django 5.2.7 on 2026-01-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_password_remove_doctor_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
